### PR TITLE
Add support for multiple dotnet versions, remove defined language version.

### PR DESCRIPTION
**Pull request by urothis**

### CODE REVIEW

**Comment by zunath** [comment]
Are any changes on the NWNX plugin side needed?

**Comment by Jorteck** [comment]
Probably shouldn't happen until EOL in May next year, as this will break any project referencing it. https://dotnet.microsoft.com/platform/support/policy/dotnet-core

**Comment by Jorteck** [comment]
Is there still a benefit of updating the sdk to 6.x, but keeping `<TargetFramework>` at `net5.0`?

**Comment by Jorteck** [comment]
> Are any changes on the NWNX plugin side needed?

I think the host APIs should be identical, though I do want to clean up the plugin at some point: https://docs.microsoft.com/en-us/dotnet/core/tutorials/netcore-hosting

**Comment by urothis** [comment]
I think this is ready for review now, I should have marked this as a draft PR before now, my apologies.

**Review by Jorteck — APPROVED** [review]

**Pull request merged**
